#!/usr/bin/env php
<?php

require "bootstrap.php";

$console = new Strukt\Console\Application();
$console->addCmdSect("Test");
$console->add(new Command\DoctrineGenerateEntities);
$console->add(new Command\CsvSanity);
$console->add(new Command\MySQLAuth);
$console->add(new Command\UserAdd);
exit($console->run($_SERVER["argv"]));
